apiVersion: apps/v1
kind: Deployment
metadata:
  # labels:
  #   app: test
  name: devops-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  strategy: {}
  template:
    metadata:
      labels:
        app: test
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: application-devops
        image: IMAGE_NAME
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "768Mi"