apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJvYXR0b21hbjc1MjIiLCJwYXNzd29yZCI6ImRja3JfcGF0X1VIZThYOVBBandlaHRIdmYtOG85RW13SmwzUSIsImF1dGgiOiJiMkYwZEc5dFlXNDNOVEl5T21SamEzSmZjR0YwWDFWSVpUaFlPVkJCYW5kbGFIUklkbVl0T0c4NVJXMTNTbXd6VVE9PSJ9fX0=
kind: Secret
metadata:
  name: dockerhub-secret
type: kubernetes.io/dockerconfigjson
