apiVersion: v1
kind: Service
metadata:
  name: devops-service
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  # selector:
  #   app: uat-app
  type: ClusterIP